name: Deploy React App to Google Cloud

on:
    push:
        branches:
            - main # Trigger the workflow on push to the main branch

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14' # Specify the Node.js version

            - name: Install dependencies
              run: npm install

            - name: Build React App
              run: npm run build

            - name: Authenticate with Google Cloud
              uses: google-github-actions/setup-gcloud@v0.2.0
              with:
                  service_account_key: ${{ secrets.GCP_SA_KEY }}
                  project_id: ${{ secrets.GCP_PROJECT_ID }}

            - name: Deploy to Google Cloud
              run: |
                  gcloud app deploy app.yaml --quiet
